version: '3.8'
services:

  rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'rest'
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/store
      - URL_HOST=thing
